/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hofapps_tinyplanet_NativeWrapper */

#ifndef _Included_org_hofapps_tinyplanet_NativeWrapper
#define _Included_org_hofapps_tinyplanet_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hofapps_tinyplanet_NativeWrapper
 * Method:    nativeLogPolar
 * Signature: (JJFFDDD)V
 */
JNIEXPORT void JNICALL Java_org_hofapps_tinyplanet_NativeWrapper_nativeLogPolar
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jdouble, jdouble, jdouble);

JNIEXPORT void JNICALL Java_org_hofapps_tinyplanet_NativeWrapper_nativeImgBlend
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_hofapps_tinyplanet_NativeWrapper
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_hofapps_tinyplanet_NativeWrapper_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
